vm:
  name: 'ftp'
  host: '192.168.1.30'
  user: np
  pwd: np
latest_dump_file:
  date: '%Y_%m_%d' # exemple: '2022_01_01'
cron:
          # Example of job definition:
          # .---------------- minute (0 - 59)
          # |  .------------- hour (0 - 23)
          # |  |  .---------- day of month (1 - 31)
          # |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...
          # |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat
          # |  |  |  |  |
          # *  *  *  *  *  user command to be executed
  syntaxe: '00 00 * * *'